syntax = "proto3";

option java_multiple_files = true;
option java_package = "taskone.proto";

/**
 * Task Management Protocol - Protocol Buffers Version
 *
 * The server currently uses JSON protocol. You need to design
 * a Protobuf version that supports the same operations:
 * - add: Add a new task
 * - list: List tasks with filter
 * - complete: Mark task as completed
 * - assign: Assign task to someone
 * - quit: Disconnect from server
 *
 * Study the JSON protocol the README.md, Server.java and Client.java to understand
 * what fields are needed for each request and response.
 */

// ========== REQUEST MESSAGES ==========

/**
 * Main request message sent from client to server.
 *
 */
message Request {
  enum RequestType {
    UNKNOWN = 0;
    ADD = 1;
    LIST = 2;
    COMPLETE = 3;
    ASSIGN = 4;
    QUIT = 5;
  }

  RequestType type = 1;

  string description = 2; //For ADD
  string priority = 3; //For ADD
  string filter = 4; //For LIST
  int32 id = 5; //For COMPLETE and ASSIGN
  string assignee = 6; //For ASSIGN
  
  
}

// ========== RESPONSE MESSAGES ==========

/**
 * Main response message sent from server to client.
 *
 */
message Response {
  enum ResponseType {
    UNKNOWN = 0;
    SUCCESS = 1;
    ERROR = 2;
  }

  ResponseType type = 1;
  bool ok = 2;
  Data data = 3;
  String req_type =4;

}

message Data {
  //ADD
  int32 id = 1;
  string description = 2;
  string priority = 3;
  string assignee = 4;
  bool completed = 5;

  //LIST
  TaskList tasks = 6;

  //COMPLETE, ASSIGN and QUIT
  string success_message = 7;

  //ERROR
  string error_message =8;

}

// ========== DATA MESSAGES ==========

/**
 * Represents a single task.
 *
 * TODO: Complete this message definition.
 * Hint: Look at Task.java to see what fields a task has.
 */
message Task_proto {
  int32 id = 1;
  string description = 2;
  string priority = 3;
  string assignee = 4;
  bool completed = 5;
}

/**
 * List of tasks (for LIST response).
 *
 * TODO: Complete this message definition if needed.
 */
message TaskList_proto {
  repeated Task tasks = 1;
  int32 count = 2;
}
